#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "No input variable provided."
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=ca-central-1" \
--query Location \
--output text