#!/usr/bin/env bash
echo "*** Create bucket ***"

if [ -z "$1" ]; then
  echo "There needs to be a bucket name e.g. ./bucket my-bucket-name"
  exit 1
fi

aws s3api create-bucket \
--bucket $1 \
--create-bucket-configuration="LocationConstraint=us-west-2" \
--query Location \
--output text

