#!/usr/bin/env bash
echo "*** Delete bucket ***"

# https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html#Bash-Conditional-Expressions
# if the length of the string is zero (-z) for the first positional argument ($1)
#Check for bucket name
if [ -z "$1" ]; then
  echo "There needs to be a bucket name e.g. ./bucket my-bucket-name"
  exit 1
fi

aws s3api delete-bucket \
--bucket $1 \
--query Location \
--output text

