#!/usr/bin/env  bash
#location to store files
if [ -z "$1" ]; then
  echo "There needs to be a bucket name e.g. ./bucket my-bucket-name"
  exit 1
fi

if [ -z "$2" ]; then
  echo "There needs to be a filename e.g. ./bucket my-bucket-name"
  exit 1
fi

BUCKET_NAME=$1
FILENAME=$2
OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY

