#!/usr/bin/env bash
echo "*** Delete objects ***"

#Check for bucket name
if [ -z "$1" ]; then
  echo "There needs to be a bucket name e.g. ./bucket my-bucket-name"
  exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > ./delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file://delete_objects.json

#will use triple slashes for absolute path e.g. file:///delete_objects.json